global
#[ALERT]    (5261) : [haproxy.main()] FD limit (200000) too low for maxconn=200000/maxsock=400036. Please raise 'ulimit-n' to 400036 or more to avoid any trouble.
#    maxconn 200000

#    maxconn 100000
    maxconn 50000
    daemon
    tune.bufsize 16384
    tune.idletimer 0
    stats socket /tmp/haproxy.sock mode 660 level admin
    tune.sched.low-latency on

    # nbproc удален, используем только потоки
    nbthread 4

    # Имя этого узла для peers
    node zx.convectix.com

    # Счётчики http_req_rate хранятся в оперативной памяти. Чтобы они гарантированно пережили «переезд» в новый процесс, лучше добавить файл состояния
    server-state-file /tmp/haproxy.state

defaults
    mode http
    option http-keep-alive
    timeout connect 5s
    timeout client  30s
    timeout server  30s

    # Это аналог tcp_nodelay, который заставляет HAProxy отправлять данные немедленно.
    option http-no-delay

    # загрузка статсы
    load-server-state-from-file global

frontend http_in
    maxconn 2000  # вместо текущих 300

    # Во FreeBSD параметр называется 'interface' или 'tfo', 
    # а reuseport включается через 'shards' или глобально. 
    # Но для одного процесса достаточно просто bind.
#    bind 127.0.0.1:80 defer-accept # http accept
    bind 127.0.0.1:80

    # В HAProxy tcp-nodelay задается через 'tcp-request content' 
    # или наследуется. Для HTTP режима он активен по умолчанию.
    default_backend nginx_static
    option http-no-delay

backend nginx_static
    balance static-rr
    option http-keep-alive
    server s1 127.0.0.1:8080 maxconn 100000
    # Попробуйте заменить на сокет для скорости:
    #server s1 /tmp/nginx.sock maxconn 100000
    option http-no-delay

# статса в CSV так:
# http://zx.convectix.com:9000/haproxy_stats;csv
listen stats
    bind *:9000
    mode http
    stats enable
    stats uri /haproxy_stats
    stats refresh 5s
    #stats admin if LOCALHOST # Позволяет менять статус серверов через браузер

peers m-w_reload
    # Указываем конкретное имя узла. 
    # В Master-Worker режиме порт можно не указывать для локальной передачи
    peer zx.convectix.com 127.0.0.1:10000

backend dynamic_limits
    # Таблица для хранения лимитов
    stick-table type ip size 100k expire 30s store http_req_rate(10s) peers m-w_reload

    # Использование современного fetch-метода:
    # Берем IP источника (src), смотрим его rate в таблице dynamic_limits
    http-request deny deny_status 429 if { src,table_http_req_rate(dynamic_limits) gt 100 }


frontend prometheus_metrics
    bind *:8404
    mode http
    no log
    # Попробуйте это имя сервиса:
    http-request use-service prometheus-exporter if { path /metrics }
