user nobody;
worker_processes 1; # или жестко 32/64 по числу ядер

events {
    worker_connections 10240;
    use kqueue;
}

http {
    access_log off;
    error_log /dev/null emerg;
    
    server {
  listen unix:/tmp/nginx1.sock;
  listen unix:/tmp/nginx2.sock;
  listen unix:/tmp/nginx3.sock;
  listen unix:/tmp/nginx4.sock;
  listen unix:/tmp/nginx5.sock;
  listen unix:/tmp/nginx6.sock;
  listen unix:/tmp/nginx7.sock;
  listen unix:/tmp/nginx8.sock;
  listen unix:/tmp/nginx9.sock;
  listen unix:/tmp/nginx10.sock;
  listen unix:/tmp/nginx11.sock;
  listen unix:/tmp/nginx12.sock;
  listen unix:/tmp/nginx13.sock;
  listen unix:/tmp/nginx14.sock;
  listen unix:/tmp/nginx15.sock;
  listen unix:/tmp/nginx16.sock;
  listen unix:/tmp/nginx17.sock;
  listen unix:/tmp/nginx18.sock;
  listen unix:/tmp/nginx19.sock;
  listen unix:/tmp/nginx20.sock;
  listen unix:/tmp/nginx21.sock;
  listen unix:/tmp/nginx22.sock;
  listen unix:/tmp/nginx23.sock;
  listen unix:/tmp/nginx24.sock;
  listen unix:/tmp/nginx25.sock;
  listen unix:/tmp/nginx26.sock;
  listen unix:/tmp/nginx27.sock;
  listen unix:/tmp/nginx28.sock;
  listen unix:/tmp/nginx29.sock;
  listen unix:/tmp/nginx30.sock;
  listen unix:/tmp/nginx31.sock;
  listen unix:/tmp/nginx32.sock;
  listen unix:/tmp/nginx33.sock;
  listen unix:/tmp/nginx34.sock;
  listen unix:/tmp/nginx35.sock;
  listen unix:/tmp/nginx36.sock;
  listen unix:/tmp/nginx37.sock;
  listen unix:/tmp/nginx38.sock;
  listen unix:/tmp/nginx39.sock;
  listen unix:/tmp/nginx40.sock;
  listen unix:/tmp/nginx41.sock;
  listen unix:/tmp/nginx42.sock;
  listen unix:/tmp/nginx43.sock;
  listen unix:/tmp/nginx44.sock;
  listen unix:/tmp/nginx45.sock;
  listen unix:/tmp/nginx46.sock;
  listen unix:/tmp/nginx47.sock;
  listen unix:/tmp/nginx48.sock;
  listen unix:/tmp/nginx49.sock;
  listen unix:/tmp/nginx50.sock;
  listen unix:/tmp/nginx51.sock;
  listen unix:/tmp/nginx52.sock;
  listen unix:/tmp/nginx53.sock;
  listen unix:/tmp/nginx54.sock;
  listen unix:/tmp/nginx55.sock;
  listen unix:/tmp/nginx56.sock;
  listen unix:/tmp/nginx57.sock;
  listen unix:/tmp/nginx58.sock;
  listen unix:/tmp/nginx59.sock;
  listen unix:/tmp/nginx60.sock;
  listen unix:/tmp/nginx61.sock;
  listen unix:/tmp/nginx62.sock;
  listen unix:/tmp/nginx63.sock;
  listen unix:/tmp/nginx64.sock;

        
        keepalive_requests 0; # отключаем keep-alive на стороне nginx
        
        location /index.html {
            return 200 "OK";
            add_header Content-Type text/plain;
        }
    }
}
